apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf
  namespace: open5gs
  labels:
    epc-mode: amf
    prometheus: open5gs-monitor
spec:
  selector:
    epc-mode: amf
  ports:
    - name: http2-open5gs-amf-80
      protocol: TCP
      port: 80 
      targetPort: 80
    - name: http-open5gs-amf-9090
      protocol: TCP
      port: 9090 
    - name: sctp-open5gs-amf-38412
      protocol: SCTP
      port: 38412
      targetPort: 38412
     # nodePort: 38412
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: open5gs-amf-sctp
#  namespace: open5gs
#  labels:
#    epc-mode: amf
#    prometheus: open5gs-monitor
#spec:
#  internalTrafficPolicy: Cluster
#  externalTrafficPolicy: Cluster
#  type: NodePort
#  selector:
#    epc-mode: amf
#  ports:
#    - name: sctp-amf
#      protocol: SCTP
#      port: 38412
      # targetPort: 38412
#      nodePort: 38412
#---